# Copyright (c) 2020-2022 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

static_library("car") {
  sources = [
    "car.c",
    "car.h",
    "car_wifi.c",
    "car_wifi.h",
    "car_websocket.c",
    "car_websocket.h",
  ]

  include_dirs = [
    "//commonlibrary/utils_lite/include",
    "//device/soc/hisilicon/ws63v100/sdk/include",
    "//device/soc/hisilicon/ws63v100/sdk/include/driver",
    "//device/soc/hisilicon/ws63v100/sdk/drivers/drivers/hal/gpio",
    "//device/soc/hisilicon/ws63v100/sdk/drivers/chips/ws63/include",
    "//device/soc/hisilicon/ws63v100/sdk/middleware/utils/common_headers",
    "//device/soc/hisilicon/ws63v100/sdk/kernel/osal/include",
    "//device/soc/hisilicon/ws63v100/sdk/kernel/osal/include/debug",
    "//device/soc/hisilicon/ws63v100/adapter/hals/iot_hardware/wifiiot_lite",
    "//base/iothardware/peripheral/interfaces/inner_api",
    "//device/board/isoh/nl63pro/sdk/drivers/peripheral/include",

    # ----- WiFi STA API -----
    "//device/soc/hisilicon/ws63v100/sdk/include/middleware/services/wifi",

    # ----- lwIP socket/netif API -----
    "//device/soc/hisilicon/ws63v100/sdk/open_source/lwip/lwip_v2.1.3/src/include",
  ]

  # mbedtls 的 include 路径由 deps 中的 public_configs 提供
  deps = [
    "//device/soc/hisilicon/ws63v100/adapter/hals/iot_hardware/wifiiot_lite:hal_iothardware",
    "//device/soc/hisilicon/ws63v100/sdk/open_source/mbedtls/mbedtls_v3.1.0:mbedtls_v3.1.0",
  ]
}
